[dependencies]
anyhow = { workspace = true }
itoa = { workspace = true }
rolldown_common = { workspace = true }
rolldown_utils = { workspace = true }
serde_json = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "rolldown_loader_utils"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
