[dependencies]
rolldown_common = { workspace = true, features = ["deserialize_bundler_options"] }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"
test = false

[lints]
workspace = true

[package]
name = "rolldown_testing_config"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
