[dependencies]
anyhow = { workspace = true }
cow-utils = { workspace = true }
heck = { workspace = true }
oxc = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
rolldown_workspace = { workspace = true }
syn = { workspace = true, features = [
  "clone-impls",
  "derive",
  "extra-traits",
  "full",
  "parsing",
  "printing",
  "proc-macro",
] }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "generator"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
