[dependencies]
anyhow = { workspace = true }
oxc = { workspace = true }
rolldown_plugin = { workspace = true }
rustc-hash = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "rolldown_plugin_build_import_analysis"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
