[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
glob = { workspace = true }
memchr = { workspace = true }
oxc = { workspace = true }
phf = { workspace = true, features = ["phf_macros"] }
rolldown_plugin = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "rolldown_plugin_dynamic_import_vars"
version = "0.0.1"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
