[dependencies]
arcstr = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
oxc_resolver = { workspace = true }
rolldown_common = { workspace = true }
rolldown_fs = { workspace = true, features = ["os"] }
rolldown_utils = { workspace = true }
sugar_path = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "rolldown_resolver"
name = "rolldown_resolver"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
