[[bench]]
harness = false
name = "bundle"

[[bench]]
harness = false
name = "scan"

[[bench]]
harness = false
name = "remapping"

[[bench]]
harness = false
name = "bundle"

[[bench]]
harness = false
name = "scan"

[[bench]]
harness = false
name = "remapping"

[dependencies]
criterion2 = { workspace = true }
oxc = { workspace = true }
rolldown = { workspace = true }
rolldown_sourcemap = { workspace = true }
rolldown_testing = { workspace = true }
rolldown_workspace = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
codspeed = ["criterion2/codspeed"]

[lib]
bench = false
doctest = false
path = "Source/lib.rs"
test = false

[package]
name = "bench"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
