[dependencies]
anyhow = { workspace = true }
arcstr = { workspace = true }
ariadne = { workspace = true }
heck = { workspace = true }
napi = { workspace = true, optional = true }
oxc = { workspace = true }
oxc_resolver = { workspace = true }
oxc_sourcemap = { workspace = true }
rolldown_utils = { workspace = true }
ropey = { workspace = true }
rustc-hash = { workspace = true }
sugar_path = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow         = { workspace = true }
arcstr         = { workspace = true }
ariadne        = { workspace = true }
heck           = { workspace = true }
napi           = { workspace = true, optional = true }
oxc            = { workspace = true }
oxc_resolver   = { workspace = true }
oxc_sourcemap  = { workspace = true }
rolldown_utils = { workspace = true }
ropey          = { workspace = true }
rustc-hash     = { workspace = true }
sugar_path     = { workspace = true }
