[package]
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "rolldown_rstr"
repository.workspace = true
version = "0.1.0"

[lib]
doctest = false

[dependencies]
oxc = { workspace = true }

[lints]
workspace = true
