[[bench]]
harness = false
name = "join"

[dependencies]
memchr = { workspace = true }
oxc = { workspace = true }
oxc_sourcemap = { workspace = true, features = ["rayon"] }
rolldown_utils = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
criterion2 = { workspace = true, default-features = false }

[lib]
bench = false
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "rolldown_sourcemap"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
