[dependencies]
anyhow = { workspace = true }
globset = "0.4"
heck = { workspace = true }
ignore = "0.4"
rolldown_workspace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true

[package]
name = "ls-lint"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true
