[dependencies]
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[lints]
workspace = true

[package]
name = "rolldown_plugin_wasm_helper"
version = "0.1.0"

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.license-file]
workspace = true

[package.repository]
workspace = true
