[dependencies]
base64-simd = { workspace = true }
regex = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils = { workspace = true }
urlencoding = { workspace = true }

[lib]
doctest = false
path = "Source/lib.rs"

[dependencies]
base64-simd     = { workspace = true }
rolldown_common = { workspace = true }
rolldown_plugin = { workspace = true }
rolldown_utils  = { workspace = true }
urlencoding     = { workspace = true }
