name: Node

concurrency:
    group: Node-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    push:
        branches: [Current]
    pull_request:
        branches: [Current]
    workflow_call:

jobs:
    Pre-Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            DO_NOT_TRACK: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0
            VCPKG_DISABLE_METRICS: 1

        strategy:
            matrix:
                node-version: [18, 19, 20]

        steps:
            - uses: actions/checkout@v4.2.1

            - uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.3.0
                  run_install: |
                      - recursive: true
                        args: [
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./docs/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./docs

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-docs-Node-${{ matrix.node-version }}-Target
                  path: ./docs/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-docs-Node-${{ matrix.node-version }}-Target
                  path: ./docs/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/basic-typescript/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/basic-typescript

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-basic-typescript-Node-${{ matrix.node-version }}-Target
                  path: ./examples/basic-typescript/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-basic-typescript-Node-${{ matrix.node-version }}-Target
                  path: ./examples/basic-typescript/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/basic-vue/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/basic-vue

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-basic-vue-Node-${{ matrix.node-version }}-Target
                  path: ./examples/basic-vue/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-basic-vue-Node-${{ matrix.node-version }}-Target
                  path: ./examples/basic-vue/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/par-plugin/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/par-plugin

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-par-plugin-Node-${{ matrix.node-version }}-Target
                  path: ./examples/par-plugin/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-par-plugin-Node-${{ matrix.node-version }}-Target
                  path: ./examples/par-plugin/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/rollup-plugin-esbuild/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/rollup-plugin-esbuild

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-rollup-plugin-esbuild-Node-${{ matrix.node-version }}-Target
                  path: ./examples/rollup-plugin-esbuild/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-examples-rollup-plugin-esbuild-Node-${{ matrix.node-version }}-Target
                  path: ./examples/rollup-plugin-esbuild/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml

            - run: pnpm install
              working-directory: .

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-Node-${{ matrix.node-version }}-Target
                  path: ./Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-Node-${{ matrix.node-version }}-Target
                  path: ./Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/bench/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/bench

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-bench-Node-${{ matrix.node-version }}-Target
                  path: ./packages/bench/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/darwin-arm64/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/darwin-arm64

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-darwin-arm64-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/darwin-arm64/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/darwin-x64/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/darwin-x64

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-darwin-x64-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/darwin-x64/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/freebsd-x64/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/freebsd-x64

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-freebsd-x64-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/freebsd-x64/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/linux-arm-gnueabihf/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/linux-arm-gnueabihf

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-linux-arm-gnueabihf-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/linux-arm-gnueabihf/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/linux-arm64-gnu/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/linux-arm64-gnu

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-linux-arm64-gnu-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/linux-arm64-gnu/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/linux-arm64-musl/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/linux-arm64-musl

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-linux-arm64-musl-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/linux-arm64-musl/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/linux-x64-gnu/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/linux-x64-gnu

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-linux-x64-gnu-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/linux-x64-gnu/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/linux-x64-musl/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/linux-x64-musl

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-linux-x64-musl-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/linux-x64-musl/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/wasm32-wasi/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/wasm32-wasi

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-wasm32-wasi-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/wasm32-wasi/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/win32-arm64-msvc/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/win32-arm64-msvc

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-win32-arm64-msvc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/win32-arm64-msvc/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/win32-ia32-msvc/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/win32-ia32-msvc

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-win32-ia32-msvc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/win32-ia32-msvc/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/npm/win32-x64-msvc/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown/npm/win32-x64-msvc

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-npm-win32-x64-msvc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/npm/win32-x64-msvc/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rolldown/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rolldown

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rolldown-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rolldown/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/rollup-tests/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/rollup-tests

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-rollup-tests-Node-${{ matrix.node-version }}-Target
                  path: ./packages/rollup-tests/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/testing/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/testing

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-packages-testing-Node-${{ matrix.node-version }}-Target
                  path: ./packages/testing/Target

            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./scripts/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./scripts

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.4.0
              with:
                  name: .-scripts-Node-${{ matrix.node-version }}-Target
                  path: ./scripts/Target
